### ISSUE TITLE
Problem with restoring connection

### ISSUE THREAD

**Issue by PawelJ-PL** [gaelrenoux/tranzactio#18]
Hi,

I observed a problem with restoring the connection when the database is unavailable for a while.
If I turn off the database I see messages  `Failed to validate connection org.postgresql.jdbc.PgConnection@60795222 (This connection has been closed.). Possibly consider using a shorter maxLifetime value`. Then from the application level I will try to make some queries (probably as many as maximum pool size or more) and get `io.github.gaelrenoux.tranzactio.DbException$Timeout: Timeout after PT1S` exception (which is obvious, because the database is not available).
However, after turning on the database, I still see the same error when trying to make a connection. Interestingly, I see on the database that the application reconnected, so HikariCP reconnection works correctly, but the application does not see a new connection. So it looks like it is not a problem with reconnections (maybe something with execution context)

**Comment by PawelJ-PL** [comment]
I did some more tests. A temporary workaround is to set the error strategy to `RetryForever` (it did not work before, but today I found information that it was fixed in version `1.0.1`, so I updated the dependencies). However, if we add `withRetryTimeout` to this, after this timeout the problem occurs again - after starting the database, the queries end up with following exception (where 5S is value of my `withRetryTimeout`):

```exception
io.github.gaelrenoux.tranzactio.DbException$Timeout: Timeout after PT5S
	at io.github.gaelrenoux.tranzactio.ErrorStrategy.$anonfun$apply$2(errorStrategy.scala:94)
	at zio.ZIO$.$anonfun$fail$1(ZIO.scala:2680)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:407)
	at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:778)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by gaelrenoux** [comment]
Hi, I'll take a look this week-end.

**Comment by PawelJ-PL** [comment]
Hi,

I've prepared small project, where you can test this problem: https://github.com/PawelJ-PL/db_problem_poc. To make it working you have to run Postgres database named `test` on `localhost:5432` with owner `test` with password `secret` (I'm using Postgres image for tests). If you would like to change this settings you can do it with environment variables according to https://github.com/PawelJ-PL/db_problem_poc/blob/master/src/main/resources/application.conf. 

When the program is started, it will display the value taken from the database every 2 seconds. At this point you can stop the database for a moment to observe the problem. By default, I have enabled the `RetryForever` strategy without timeout and in this case it works as it should (after starting the database the application is able to work normally). To test the incorrect behavior just change `dbWithoutRetryTimeout` to`dbWithRetryTimeout` or `dbWithDefaultErrorStrategy` in linehttps://github.com/PawelJ-PL/db_problem_poc/blob/master/src/main/scala/poc/Layers.scala#L35. Then, after turning the database off and on again after a while, the application still returns the `io.github.gaelrenoux.tranzactio.DbException$Timeout: Timeout after PT1S` exception

**Comment by gaelrenoux** [comment]
Thanks for the project, it provided a great starting point. After quite a few hours working on that, I'm pretty confident that I made a mistake in allowing to set timeouts for opening connections. Here's the issue when ZIO aborts the openConnection method with a timeout:
- on tranzactio's side, the whole transaction is aborted, and we can't close the connection (since we have no connection to close) ;
- on the other hand, HikariCP might complete its method, returning a connection that will be out of the pool, but cannot be released ever.

This connection leak is what caused your issue. When the DB comes back online, there are typically several pending openConnection methods (aborted from tranzactio's point of view, still running from HikariCP's point of view). These methods will get connections, and rapidly deplete the connection pool.

I'm currently wondering whether I should remove the timeouts on the openConnection method only, or on all methods. Without a global retryTimeout, I also need to add some commodity methods on the ErrorStrategies to set the retry schedule (not just the duration), as the only way to do that right now is cumbersome:
`ErrorStrategies.all(ErrorStrategy(Schedule.recurs(5) && Schedule.spaced(1.second) , Duration.Infinity, Duration.Infinity))`

 In the meantime, I would recommend that:
- you remove all timeouts from your tranzactio configuration;
- you use a max number of retries instead of `withRetryTimeout`;
- you rely entirely on your connection pool's configuration parameters to handle timeouts (especially setConnectionTimeout in HikariCP, when getting a connection).

**Comment by gaelrenoux** [comment]
I'll try to work on it again this week, and to provide a new version next week-end.

**Comment by PawelJ-PL** [comment]
Thank you for your analysis and taking up the issue. Currently I will set up the connection configuration based on HikariCP and I will follow the thread.
