### ISSUE TITLE
Handling multiple databases

### ISSUE THREAD

**Issue by etandon-coatue** [gaelrenoux/tranzactio#34]
Looking for direction on handling multiple databases. For example, we have an application that reads from Postgres and Snowflake. 
Would the best approach be to make multiple package objects extending wrapper(one for each DB) or is there a more elegant way to do this?

**Comment by gaelrenoux** [comment]
My first idea is that you should have two different layers, one for each of the databases you want to handle. You could make these appear in the type signature of the layer by using different types for the two of them.

It's a bit more complicated to have tzio queries force one DB or the other. I think you would need to create your own wrapper around Tranzactio, where you would add a requirement on the ZIO for a specific DB, just as a marker. Instead of calling tzio, you'd call (for example) `tzioPostgres`, which would return a `ZIO[Connection with Postgres, E, A]`. Calling the Database module's method on them would give you a `ZIO[Database with Postgres, E, A]`. Then, you would have the two layers, one providing a `Database with Postgres`, and another one a `Database with Snowflake`.

Not sure if that answers your question? In any case, there's nothing planned in TranzactIO to explicitly handle this.
