### ISSUE TITLE
Upgrade zio-interop-cats version

### ISSUE THREAD

**Issue by dirkdior** [gaelrenoux/tranzactio#43]
The current `zio-interop-cats` version in the project has no support for ZIO 2, hence there are `no implicit found` errors when constructing the `Transactor[Task]` for Doobie.
`

**Comment by gaelrenoux** [comment]
Which version of `tranzactio` are you using? It only supports ZIO 2 starting at version `4.0.0`. If you are using a correct version, I don't think the issue comes from this side: `tranzactio` is using version `3.3.0` of `zio-interop-cats`, which is build on ZIO 2 (cf https://github.com/zio/interop-cats/blob/v3.3.0/build.sbt#L50). Do you have another version coming from somewhere?

**Comment by dirkdior** [comment]
Actually no, I was using the latest version of `tranzactio` but was unable to construct the `Transactor[Task]` for Doobie as version `3.3.0` of `zio-interop-cats` does not contain the implicit for converting `Transactor[IO]` to `Transactor[Task]`, which the latest version of `zio-interop-cats` handles well as seen in the documentation (https://github.com/zio/interop-cats#example).

**Comment by gaelrenoux** [comment]
I've upgraded to the latest version of zio-interop-cats (23.0.0.5), tell me if the problem still appears. Sorry for the long delay !
